### ISSUE TITLE
Need a standard structure for oseps

### ISSUE THREAD

**Issue by trickvi** [openspending/osep#1]
I feel we need a standard structure for _oseps_ if this is supposed to be useful. Something similar to [PEP 001](http://www.peps.io/1/), for example [what belongs in a successful PEP](http://www.peps.io/1/#id33) and [PEP header preamble](http://www.peps.io/1/#id35).

At the moment I don't see the two proposals as being anything different than a long email thread (which one of them already is although no conclusion has been reached -- we also don't have an approval process for the oseps).

**Comment by rufuspollock** [comment]
Good idea - do you want to make some suggestions.

From my end I feel we could come back after we've done the first 1 or 2 as these could inform the guidelines.

**Comment by pwalsh** [comment]
I strongly agree with the original suggestion. A bit more structure and a clear guideline for OSEPs can make the documents more accessible.

I've now had a good look at the existing OSEPs with this in mind, and referenced [PEP01](https://www.python.org/dev/peps/pep-0001/) and [PEP09](https://www.python.org/dev/peps/pep-0009/) in the process.

Seeing as I'm currently working on OSEP04 and probably other OSEPs too, I'm planning to do the following (asap), unless I get a strong objection:
- create OSEP-00 to describe a very lightweight pattern for OSEPs, based on PEP-1 and PEP-9
- Ensure that OSEP04 follows this pattern
- Do simple formatting on other OSEPs to conform to the pattern

This is a small amount of additional work now (a couple of hours) but will give a better framework going forward.

Based on all of the above, the structure of an OSEP should be:
- Front matter
- Overview
- Background
- Proposal
- Appendix

Additionally:
- each OSEP must be in markdown (possibly obvious)
- each OSEP (once "live") must have an issue associated with it for comments, and a link to that issue from the top and bottom of the proposal

**Comment by rufuspollock** [comment]
@pwalsh ++1 - also note the standard jekyll frontmatter structure (which can be adapted / extended).
