### ISSUE TITLE
File naming conventions for OSEPs

### ISSUE THREAD

**Issue by pwalsh** [openspending/osep#10]
@rgrp @tryggvib 

Currently, the OSEPs are named with a prefix of the number and then a slug based on the heading.

I think this should be changed to this pattern:

`osep-{NUMBER}.md`

This will make it easier to reference URLs without knowing them. 

We can support redirects from current to this pattern for the OSEPs that already exist.

**Comment by rufuspollock** [comment]
@pwalsh good idea. Please dive in :-)
