### ISSUE TITLE
Profile description is inconsistent

### ISSUE THREAD

**Issue by trickvi** [openspending/osep#16]
It is unclear, except for from the examples how to structure the "profiles" top level attribute. Also the spec says it should be an array, but the example shows it as a hash. That's inconsistent. The open discussion on dataprotocols we're directed to does not have a suggested resolution.

**Comment by stevage** [comment]
I think the plan for `profiles` evolved a bit, see https://github.com/dataprotocols/dataprotocols/issues/87#issuecomment-120723516

TL;DR: the doc is out of date, and it should be a hash, as in the example. (Well, I'm not sure what the "*" is supposed to represent).

**Comment by rufuspollock** [comment]
FIXED. INVALID. I actually think we won't require profiles stuff for the moment. May add it later but I'd want to think more about what value it delivers. Maybe it should be a SHOULD not a MUST etc.
