### ISSUE TITLE
Owner attribute relating to a specific system doesn't fit into a package that can be shipped around

### ISSUE THREAD

**Issue by trickvi** [openspending/osep#17]
The owner attribute is weird. OSDPs should be independent and reusable in other systems. Using OpenSpending.org user names is therefore just weird, you're tying an independent format into a specific platform. OpenSpending.org should keep track of this on its own, the data package format shouldn't.

**Comment by rufuspollock** [comment]
I get  that we could leave this out and it is part of the general DataStore interface to have this set as part of the API.

I was thinking of this in the actual datapackage.json a bit like you get "organization / user" in the github metadata on a repo.

Right now I think we can drop and drop from the spec and revisit (simpler is always better if in doubt)
