### ISSUE TITLE
Defaults will lead to problems, especially currency default

### ISSUE THREAD

**Issue by trickvi** [openspending/osep#18]
I've said this before but the defaults are very weird and I wouldn't have them there at all. Defaulting to USD is especially weird. If we want to have defaults we should base them on the most commonly used currency, most widely used currency (base currency of the most countries) or the currency of the most used currency in OpenSpending.org which is Japanese Yen (395 datasets compared to 24 from the US) or get behind the "terra" or DEY camps for a world currency. Best would be to just not have any default at all.

**Comment by rufuspollock** [comment]
Shall we switch to having no default currency? Makes sense to me.

**Comment by stevage** [comment]
Yeah, IMHO having a default currency built into the system has few benefits and is likely to cause the occasional WTF. Better that imports/validators reject a file when the currency isn't specified than make that assumption.

**Comment by stevage** [comment]
Although one downside with simply making it mandatory is then [it needs to specified on every source](https://github.com/stevage/osep/commit/497f37613dcbf941e810ef29c9bf809654f868e5). I don't know whether that's an issue - do people typically have many sources?

Some way to specify package-level defaults might be useful.

**Comment by stevage** [comment]
As for the others:
- `granularity=aggregated`: Seems problematic.
- `direction=expenditure`: Borderline. "expenditure" is a natural default for Open _Spending_ but it's probably still going to trip some people up.
- `status=approved`: Not sure what the implications are if this is wrong - just bad metadata? Maybe ok, although it seems a bit arbitrary (could just as easily have been `adjusted` or `executed`)
- `factor=1`: Seems ok. 1 is a totally predictable default.

**Comment by pwalsh** [comment]
I think we'll remove these defaults from the spec.

**Comment by rufuspollock** [comment]
FIXED.
