### ISSUE TITLE
Overview Diagram for OpenSpending Tech Work

### ISSUE THREAD

**Issue by rufuspollock** [openspending/osep#2]
Based on discussion with @tryggvib here is an overview of OpenSpending tech work that summarizes some of the points in OSEP 1 and OSEP 2 (may embed into a revised OSEP 1) and provides a basis for discussion.

To be clear this is about responsibilities of OS Tech efforts - e.g. it may well be that folks from OS community working on presenting info (and building WDMMG sites etc) but it wouldn't be something that OS Tech effort were responsible for making happen.

<img src="https://docs.google.com/drawings/d/1s5MtY_6LlYwi1e0_vjjYQW5Z29SzzHe6W0Rr1sm4HB0/pub?w=903&amp;h=793">

**Comment by pwalsh** [comment]
This diagram is part of [OSEP-01](http://labs.openspending.org/osep/osep-01.html), which has been accepted. 

There is also now a dedicated [discussion thread for OSEP-01](https://github.com/openspending/osep/issues/3).

So, closing this issue.
