### ISSUE TITLE
Functional classification becomes a "dirty hack" when you already use COFOG

### ISSUE THREAD

**Issue by trickvi** [openspending/osep#20]
Functional classification mapping is weird when you already have COFOG and (and also when it's split across three fields). An id is a must and cofog is a may. Why have a unique id for COFOG when COFOG is already a unique code (as per the example which has function.id as 1,2,3 which maps to different COFOG codes? Cofog can just be the foreign key to a table with a description of that COFOG code (that's how things were designed for budget data packages).

**Comment by pwalsh** [comment]
@tryggvib we needs some examples to talk around. 

I definitely would not expect most or even a majority of data for OS to have COFOG mappings at this time. COFOG is also extremely limited, being only applicable to expenditure.

**Comment by rufuspollock** [comment]
Let's focus this on ways we can efficiently map taxonomies when they are split over multiple columns. Question of whether COFOG is special cased (probably not) can be left for now i think.

**Comment by rufuspollock** [comment]
INVALID / FIXED.
