### ISSUE TITLE
Including both resource and field name in one property makes parsing the json difficult (in some cases)

### ISSUE THREAD

**Issue by marek-dudas** [openspending/osep#26]
The format of mapping.attribute.resource “{RESOURCE_NAME}/{FIELD_NAME}” makes transformation of OSDP into RDF just with JSON-LD context and SPARQL nearly impossible. Splitting it into two properties would make it easier.

Proposal: each property in mapping must have subproperties _resource_ and _field_
- resource: resource name equal to some _resources[i].name_
- field: field name equal to some _resources[i].schema.fields[j].name_

**Comment by rufuspollock** [comment]
Agreed. We will separate these out.
