### ISSUE TITLE
Mapping to multiple resources in one OSDP is convenient for data producer but makes the job of data consumer harder

### ISSUE THREAD

**Issue by marek-dudas** [openspending/osep#27]
If a property is mapped to several resources, e.g., "date": ["budget1/year", "budget2/year"], it might be difficult to parse the json, especially if a group of normalized tables is also included. Transforming such json with json-ld context and SPARQL updates is then nearly impossible.

Proposal: put mapping into separate file: each resource or group of interconnected normalized resources (tables) have its own JSON file with mappings
each OSDP would thus have
- one _description_ json object with properties name, title, profiles, location, granularity, direction and status
- one or more _mapping_ json objects

See _Proposal 2_ in https://goo.gl/1HSZSk for more details and examples.

**Comment by rufuspollock** [comment]
FIXED / WONTFIX. Agree with you this is an issue and that we will remove this. I think we actually do not allow split files _or_ implement some way to concatenate - see #30
