### ISSUE TITLE
Setting one currency for the whole data package might be too restrictive: a proposal of a new mapping property

### ISSUE THREAD

**Issue by marek-dudas** [openspending/osep#29]
Proposal: add mapping property _currency_
- overrides _mapping.amount.currency_ value if present
- this would allow payments in different currencies in one file

**Comment by rufuspollock** [comment]
I agree that in addition to setting a value for the whole dataset you should be able to set this from a column/field in the source.

**Comment by jindrichmynarz** [comment]
To generalize this issue, we may consider something similar to the attachment level ([`qb:attachmentLevel`](http://www.w3.org/TR/vocab-data-cube/#ref_qb_componentAttachment)) from the Data Cube Vocabulary (see e.g., [data abbreviation](http://www.w3.org/TR/vocab-data-cube/#h2_normalize)) to allow a component (~ JSON property) to be attached at different levels of granularity; e.g., currency stated for the whole dataset or individual transactions.

**Comment by rufuspollock** [comment]
@jindrichmynarz i get you though i would be wary here of adding complexity we would not need. The direction we've gone is that currency is now set when you define the measure and hence is per "column".  I think we also need to support the case where currency is itself a column.

**Comment by rufuspollock** [comment]
FIXED. In Fiscal Data Package currency is an attribute of measure.

**Comment by rufuspollock** [comment]
See also https://github.com/openspending/fiscal-data-package/issues/76
