### ISSUE TITLE
[4-osdp] Concatenation and support or data split over multiples files

### ISSUE THREAD

**Issue by rufuspollock** [openspending/osep#30]
We currently have a use case to support situations where the data is spread over multiple files e.g.

```
budget1.csv
amount, date

budget2.csv
amount,data
```

It is also possible that "normalized" files e.g. payee information is also split over multiple csv files.

Rather than addressing this in the mapping by having to reference multiple files from each mapped attribute I propose that instead we have some way to indicate that files should be concatenated e.g. in mapping attribute or similar we have:

```
concatentations: [
  ["budget1.csv", "budget2.csv", ...],
  ["payee1.csv", "payee2.csv"]
]
```

I think this is a better solution because:
- It makes explicit the implicit assumption that these files have the same structure
- It is simpler to implement
- It keeps the mapping simple - you maps against the primary files e.g. budget1.csv or payee1.csv

**Comment by pudo** [comment]
Looks to me like you're heading pretty far down the route of building an ETL tool here. Are you sure that describing ETL operations should be within the scope of the core metadata? Is it useful to bring in all this complexity before there is a prototype that you can iterate on? Just me two cents...

**Comment by rufuspollock** [comment]
@pudo i either think concatentations are out of scope (i.e. you can't have data in multiple files) or you need a way to support them in describing the mapping. I would generally agree we don't need this in the prototype - hence this issue (as I am about to remove support for data split over multiple files from the spec whilst we discuss this).

**Comment by jindrichmynarz** [comment]
I'm with @pudo that here you describe the ETL process and not the data. If describing ETL processes (even simple operations as file concatenation) as structured data is demanded, then it would be better addressed in a separate specification.

**Comment by rufuspollock** [comment]
@jindrichmynarz I hear you. The question here i think is the trade-off of accommodating "split" datasets (which are common) and adding something that is a bit "out of place" in the spec. Either we can forbid split datasets (which excludes some sources) or we need a way to handle them. How would you propose we do it?

**Comment by pudo** [comment]
How would forbidding split datasets exclude them from OS? All you need is to [`csvstack`](http://csvkit.readthedocs.org/en/latest/scripts/csvstack.html) them before loading.

**Comment by jindrichmynarz** [comment]
I think it's reasonable to expect users to do _elementary ETL_ (such as using the above-mentioned `csvstack`) rather than trying to describe all formats and shapes the users' data might have.

**Comment by rufuspollock** [comment]
@pudo right but how do you indicate that in the description of the physical CSV files. The idea is that OS DP is able to describe the files as they are on disk (or we require that they are already csvstack'd ...)

**Comment by jindrichmynarz** [comment]
Would adding a Makefile into /scripts solve this?

**Comment by pudo** [comment]
@rgrp hm, I guess that comes down to a more fundamental issue I have with data packages; i.e. I struggle to see the value in describing files for the description's sake; I think the metadata should exist in relation to some process (e.g. loading data into OS or similar). Process is a separate concern and can be expressed really nicely in a `Makefile`.

**Comment by pwalsh** [comment]
I thought about this more. I think we should _definitely_ support the basic use case of multiple files of the "same" data, and we should do it as part of the core Tabular Data Package spec, on a `resource` object.

eg: given:

```
budget1.csv
amount, date

budget2.csv
amount,date
```

We would not have 2 distinct resources: rather, we'd allow `path`, `data` and `url` to be arrays:

```
{
  "name": "My Stuff",
  "resources": [
    {
      "path": ["budget1.csv", "budget2.csv"]
    }
  ]
}
```

I don't like having a distinct "concatenations" property: this pattern is a much better representation of the thing we are describing IMHO, and simply extends what already exists.

I agree that this is blurring a line between ETL and metadata. 

I think the pros outweigh the cons considering how common this really is out in the wild.

In the various libs that exist and will be further developed for dealing with DataPackages and resources therein, it is just trivial to extend iteration patterns over files to work on an array of them, or, perform some concat first and internally treat the files as one thing (`shutil.copyfileobj`, or whatever is behind `csvstack`, for example).

**Comment by rufuspollock** [comment]
DUPLICATE of https://github.com/openspending/fiscal-data-package/issues/75
