### ISSUE TITLE
[OSEP-04] Open Spending Data Package

### ISSUE THREAD

**Issue by pwalsh** [openspending/osep#6]
Comments for [OSEP-04](http://labs.openspending.org/osep/04-openspending-data-package.html)

**Comment by pudo** [comment]
I just wanted to put the comments from openspending-dev (https://lists.okfn.org/pipermail/openspending-dev/2015-April/001129.html, https://lists.okfn.org/pipermail/openspending-dev/2015-May/001132.html) on the record as a proposed change for OSEP-4. I believe it would be a severe mistake to go ahead with the purely column-based model for the reasons outlined in these messages.

**Comment by pwalsh** [comment]
Edit: I started a thread for general discussion on OSDP and data structure on OS [here](https://discuss.okfn.org/t/open-spending-data-structure-ideas-and-suggestions/300), and @pudo has added his comments there. 

This thread is still for specific comments on OSEP-04.

**Comment by trickvi** [comment]
I guess you want all comments for OSEP-04 to be in this thread. Here are a few comments I have:
- It is unclear, except for from the examples how to structure the "profiles" top level attribute. Also the spec says it should be an array, but the example shows it as a hash. That's inconsistent. The open discussion on dataprotocols we're directed to does not have a suggested resolution.
- The owner attribute is weird. OSDPs should be independent and reusable in other systems. Using OpenSpending.org user names is therefore just weird, you're tying an independent format into a specific platform. OpenSpending.org should keep track of this on its own, the data package format shouldn't.
- I've said this before but the defaults are very weird and I wouldn't have them there at all. Defaulting to USD is especially weird. If we want to have defaults we should base them on the most commonly used currency, most widely used currency (base currency of the most countries) or the currency of the most used currency in OpenSpending.org which is Japanese Yen (395 datasets compared to 24 from the US) or get behind the "terra" or DEY camps for a world currency. Best would be to just not have any default at all.
- There needs to be an explicit way for attribute groups to work across different datasets. For example, the `payer` attribute group will in a normalised set up have an id in the budget resource which is a foreign key to an id in another resource which contains the title and perhaps the description. It's not clear how this should be handled and it needs to be explicit.
- Functional classification mapping is weird when you already have COFOG and (and also when it's split across three fields). An `id` is a must and `cofog` is a may. Why have a unique id for COFOG when COFOG is already a unique code (as per the example which has `function.id` as 1,2,3 which maps to different COFOG codes? Cofog can just be the foreign key to a table with a description of that COFOG code (that's how things were designed for budget data packages).
- Also we need a way to create a combined value, e.g. `id`. For example COFOG code is split across three fields (`level1`, `level2` and `level3`). We should be able to combine those into one field `level1.level2.level3`.

**Comment by pwalsh** [comment]
@tryggvib did you see my comments on these points in trello yesterday?

Some are discussed in the https://discuss.okfn.org/t/open-spending-data-structure-ideas-and-suggestions/300/22

It would be great if you can make some suggestions for change, and/or engage on existing discussions for some issues.

Specifically, for the functional mapping: tell me if I am wrong, but it seems you are equating functional classification with COFOG, whereas the intention was that a local functional classification system can be mapped to COFOG.

**Comment by rufuspollock** [comment]
@pwalsh I and @tryggvib saw comments and I suggested he post some issues here as they might lead to actual amendments (e.g. we may remove owner attribute).

@tryggvib could we post these items as separate issues here in OSEP tracker and we discuss them individually rather than en masse.

**Comment by trickvi** [comment]
@pwalsh no I'm not equating functional classification with COFOG. My two points are when you have COFOG (which many already have as that's e.g. the Eurostat standard) it becomes hackish and local functional classifications run into the same problems with multiple attributes having to be compound into an id because of hierarchies (they're almost all hierarchical classifications).

@rgrp I can post these as separate items in the tracker but @pwalsh did request to have specific comments to OSEP-4 posted into this thread:

> This thread is still for specific comments on OSEP-04.

This means a change in direction (I'm fine with that but I think @pwalsh should be in on it/approve so we don't screw up with his initial plan).

**Comment by rufuspollock** [comment]
@tryggvib i would suggest splitting - even if this is a the generic thread. It will make discussion so much more productive.

**Comment by pwalsh** [comment]
@tryggvib it is cool, it doesn't have to be that formal :). Whatever best suits the needs of the problem.

**Comment by trickvi** [comment]
Discussion moved to separate tickets:
- https://github.com/openspending/osep/issues/16
- https://github.com/openspending/osep/issues/17
- https://github.com/openspending/osep/issues/18
- https://github.com/openspending/osep/issues/19
- https://github.com/openspending/osep/issues/20
- https://github.com/openspending/osep/issues/21

**Comment by stevage** [comment]
Belated suggestion: you could add Github labels, like [OSEP-04] to group them.

**Comment by pwalsh** [comment]
Go here for help and to raise issues: https://github.com/openspending/fiscal-data-package/issues
